version: "3"
services:
  db:
    image: postgres
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: doctor
      POSTGRES_USER: doctor
      POSTGRES_DB: doctor
    ports:
      - "3030:5432"
  web:
    image: muffassa/diploma-server:latest
    networks:
      - webnet
    environment:
      DB_HOST: db
    command: ["./wait-for-it.sh", "db:5432", "--", "node", "index.js"]
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
    ports:
      - "80:80"
    networks:
      - webnet
    depends_on:
      - web
    links:
    - web:web
    command: /bin/bash -c "cat /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
networks:
  webnet: